spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

logging:
  level:
    jdbc:
      audit: DEBUG
      sqlonly: DEBUG
      resultset: DEBUG
      resultsettable: DEBUG
