spring:
  application:
    name: carematching
  config:
    import: optional:file:.env[.properties]
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        use_sql_comments: 'true'
        temp:
          use_jdbc_metadata_defaults: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://${DB_IP}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  devtools:
    restart:
      enabled: 'true'
mybatis:
  type-aliases-package: com.sesac.carematching
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    jdbc:
      audit: DEBUG
      sqlonly: DEBUG
      resultset: DEBUG
      resultsettable: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
