spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

logging:
  level:
    jdbc:
      audit: INFO
      sqlonly: INFO
      resultset: INFO
      resultsettable: INFO
